---

- name: Set variables
  set_fact:
    hitchhiker_config:
      type: "{{ hitchhiker_type }}"
      name: "{{ hitchhiker_name }}"
      timezone: "{{ hitchhiker_timezone | default(None) }}"
      exposed_ports: "{{ hitchhiker_exposed_ports | default(None) }}"
      network_mode: "{{ hitchhiker_network_mode | default('bridge') }}"
      networks: "{{ hitchhiker_neworks | default(None) }}"
      gps:
        latitude: "{{ hitchhiker_latitude | default(None) }}"
        longitude: "{{ hitchhiker_longitude | default(None) }}"
        altitude: "{{ hitchhiker_altitude | default(None) }}"
      url:
        external: "{{ hitchhiker_external_url | default (None) }}"
        internal: "{{ hitchhiker_internal_url | default (None) }}"
      storage:
        internal: "{{ hitchhiker_internal_storage_dir | default('') }}"
        config: "{{ hitchhiker_config_dir | default('/config') }}"
        public: "{{ hitchhiker_public_storage_dir | default('') }}"
    hitchhiker_default_build_args:
      BUILD_FROM: "homeassistant/{{ hitchhiker_build_arch }}-base-python:3.8-alpine3.12"
      LOADER_VERSION: "{{ hitchhiker_base_version }}"
      BUILD_ARCH: "{{ hitchhiker_build_arch }}"
      COMPONENTS: >
        {% for component in (homeassistant_components | default([])) %}
        {{ component.source }} {{ component.name }} {{ component.version }}\n
        {% endfor %}
    hitchhiker_image_build_args: "{{ hitchhiker_build_args | default({}) | combine((hitchhiker_default_build_args | default({}))) }}"

- name: Set facts from config
  set_fact:
    hitchhiker_default_container_mounts:
      - "{{ hitchhiker_config.storage.config }}:/config"
      - "{{ hitchhiker_config.storage.internal is defined | ternary(hitchhiker_config.storage.internal ~ ':/config/.storage', None) }}"
      - "{{ hitchhiker_config.storage.public is defined | ternary(hitchhiker_config.storage.public ~ ':/config/www', None) }}"
      - /etc/localtime:/etc/localtime:ro
    docker_build_images:
      basehitchhiker:
        repo: https://github.com/constructorfleet/homeassistant-loader-docker.git
        branch: master
        buildargs: "{{ hitchhiker_image_build_args }}"
        target: base
      hitchhikerintegration:
        repo: https://github.com/constructorfleet/homeassistant-loader-docker.git
        branch: master
        buildargs: "{{ hitchhiker_image_build_args }}"
        target: integration

- name: Set fact for docker container
  set_fact:
    docker_containers: |
      {
        "hitchhiker_{{ hitchhiker_config.name }}": {
          "name: "{{ hitchhiker_config.name }}",
          "image": "hitchhikerintegration",
          "description": "{{ hitchhiker_config.name }} integration",
          "container_name": "hitchhiker_{{ hitchhiker_config.name | lower | replace('-', '_') | replace(' ', '_') }}",
          "restart: "unless-stopped",
          "networks: "{{ hitchhiker_networks }}",
          "ports": "{{ hitchhiker_config.exposed_ports }}",
          "volumes": "{{ hitchhiker_default_container_mounts | select('ne', None) | list | unique }}",
          "logging": {
            "driver": "journald",
            "options": {
              "tag": "{{ hitchhiker_config.name }}"
            }
          }
        }
      }

- name: Ensure the configuration path exists
  file:
    state: directory
    path: "{{ hitchhiker_config.storage.config }}"

- debug:
    var: hitchhiker_config
- debug:
    var: hitchhiker_name

#- name: Ensure the internal path exists
#  file:
#    state: directory
#    path: "{{ hitchhiker_config.storage.internal }}"
#  when:
#    - hitchhiker_config.storage.internal is defined
#    - hitchhiker_config.storage.internal | default(False)

- name: Template out the customization file
  template:
    src: homeassistant/customization.yaml.j2
    dest: "{{ hitchhiker_config.storage.config }}/customization.yaml"

- name: Template out the configuration file
  template:
    src: homeassistant/configuration.yaml.j2
    dest: "{{ hitchhiker_config.storage.config }}/configuration.yaml"