---

- name: Deploy/Update a Home-Assistant integration
  import_tasks: homeassistant.yml
  when:
    - (hitchhiker_type | lower) == 'homeassistant'

- name: Create/Set-up docker networks and containers
  include_role:
    name: docker

- name: Restart container if needed
  systemd:
    name: "docker-hitchhiker_{{ hitchhiker_config.name }}"
    state: restarted
  when:
    - docker_service is not changed
    - customization_file is changed or configuration_file is changed


