---

- name: Verify variables are valid and set
  include_tasks: validate_variables.yml

- name: Set configuration data fact
  set_fact:
    hitchhiker_config:
      type: "{{ hitchhiker_type }}"
      name: "{{ hitchhiker_name }}"
      timezone: "{{ hitchhiker_timezone | default(None) }}"
      exposed_ports: "{{ (hitchhiker_exposed_ports | default([])) + [hitchhiker_exposed_ui_port | int] }}"
      ui_port: "{{ hitchhiker_exposed_ui_port | int }}"
      network_mode: "{{ hitchhiker_network_mode | default('bridge') }}"
      networks: "{{ hitchhiker_neworks | default(None) }}"
      gps:
        latitude: "{{ hitchhiker_latitude | default(None) }}"
        longitude: "{{ hitchhiker_longitude | default(None) }}"
        altitude: "{{ hitchhiker_altitude | default(None) }}"
      url:
        external: "{{ hitchhiker_external_url | default (None) }}"
        internal: "{{ hitchhiker_internal_url | default (None) }}"
      storage:
        internal: "{{ hitchhiker_internal_storage_dir | default(None) }}"
        config: "{{ hitchhiker_integration_config_dir }}"
        public: "{{ hitchhiker_public_storage_dir | default(None) }}"
    hitchhiker_default_build_args:
      BUILD_FROM: "{{ hitchhiker_build_from }}"
      LOADER_VERSION: "{{ hitchhiker_base_version }}"
      BUILD_ARCH: "{{ hitchhiker_build_arch }}"
      COMPONENTS: "{{ hitchhiker_components | default([]) | join('\n') }}"

- name: Remove all configuration if recreating
  file:
    state: absent
    path: "{{ path }}"
  loop:
    - "{{ hitchhiker_config.storage.config | default(None) }}"
    - "{{ hitchhiker_config.storage.internal | default(None) }}"
    - "{{ hitchhiker_config.storage.public | default(None) }}"
  loop_control:
    loop_var: path
  when:
    - path != None
    - hitchhiker_recreate | default(False)

- name: Remove all configuration if recreating
  file:
    state: directory
    path: "{{ path }}"
  loop:
    - "{{ hitchhiker_config.storage.config | default(None) }}"
    - "{{ hitchhiker_config.storage.internal | default(None) }}"
    - "{{ hitchhiker_config.storage.public | default(None) }}"
  loop_control:
    loop_var: path
  when:
    - path != None

- name: Set build args
  set_fact:
    hitchhiker_image_build_args: "{{ hitchhiker_build_args | default({}) | combine((hitchhiker_default_build_args | default({}))) }}"

- name: Deploy/Update a Home-Assistant integration
  import_tasks: homeassistant/configure.yml
  when:
    - (hitchhiker_type | lower) == 'homeassistant'

- name: Create/Set-up docker networks and containers
  include_role:
    name: docker

- name: Restart container if needed
  systemd:
    name: "docker-hitchhiker_{{ hitchhiker_config.name }}"
    state: restarted
  when:
    - docker_service is not changed
    - customization_file is changed or configuration_file is changed

- name: Wait for container to start
  wait_for:
    host: '{{ ansible_fqdn }}'
    port: '{{ hitchhiker_config.exposed_ports | first | default(omit) }}'
    timeout: 45

- name: Set hitchhiker url fact
  set_fact:
    hitchhiker_url: '{{ hitchhiker_uri_scheme }}://{{ ansible_fqdn }}{{ hitchhiker_config.exposed_ports  :{{ homeassistant_port }}'
    hitchhiker_url_schemeless: '{{ ansible_fqdn }}:{{ homeassistant_port }}'







