---

- name: Deploy/Update a Home-Assistant integration
  import_tasks: homeassistant.yml
  when:
    - (hitchhiker_type | lower) == 'homeassistant'

- name: Create/Set-up docker networks and containers
  include_role:
    name: docker

- name: Restart container if needed
  systemd:
    name: "docker-hitchhiker_{{ hitchhiker_config.name }}"
    state: restarted
  when:
    - docker_service is not changed
    - customization_file is changed or configuration_file is changed

- name: Wait for container to start
  wait_for:
    host: '{{ ansible_default_ipv4.address }}'
    port: '{{ homeassistant_port | int }}'
    sleep: 2

- name: Set homeassistant_url fact
  set_fact:
    homeassistant_url: '{{ hitchhiker_uri_scheme }}://{{ ansible_hostname }}:{{ homeassistant_port }}'

- name: Create Home-Assistant admin user
  uri:
    url: '{{ homeassistant_url }}/api/onboarding/users'
    method: POST
    body: |
      {"client_id":"{{ homeassistant_url }}/","name":"{{ homeassistant_name | default('admin')}}","username":"{{ homeassistant_username | default('admin')}}","password":"{{ homeassistant_password }}","language":"en"}
    return_content: yes
  register: user_onboarding

- name: Set authorization code fact
  set_fact:
    authorization_code: '{{ user_onboarding.content | regex_replace("^.*\"auth_code\": \"(.*)?\".*$", "\\1") }}'

- name: Get refresh token for admin user
  uri:
    url: '{{ homeassistant_url }}/api/auth/token'
    method: POST
    body:
      client_id: '{{ homeassistant_url }}/'
      code: '{{ authorization_code }}'
      grant_type: authorization_code
    return_content: yes
  register: refresh_token

- debug:
    var: refresh_token





