---

- name: Deploy/Update a Home-Assistant integration
  import_tasks: homeassistant.yml
  when:
    - "{{ (hitchhiker_type | lower) == 'homeassistant' }}"

- name: Create/Set-up docker networks and containers
  include_role:
    name: docker
#    apply:
#      vars:
#        docker_build_imags: '{{ docker_build_images }}'
#        BUILD_FROM: "{{ BUILD_FROM }}"


