---

- name: Set facts from config
  set_fact:
    hitchhiker_default_container_mounts:
      - "{{ hitchhiker_config.storage.config }}:/config"
      - "{{ hitchhiker_config.storage.internal is defined | ternary(hitchhiker_config.storage.internal ~ ':/config/.storage', None) }}"
      - "{{ hitchhiker_config.storage.external is defined | ternary([hitchhiker_config.storage.external ~ ':/config/www'], None) }}"
      - /etc/localtime:/etc/localtime:ro
    docker_build_images:
      basehitchhiker:
        repo: https://github.com/constructorfleet/homeassistant-loader-docker.git
        branch: master
        buildargs: "{{ hitchhiker_image_build_args }}"
        target: base
      hitchhikerintegration:
        repo: https://github.com/constructorfleet/homeassistant-loader-docker.git
        branch: master
        buildargs: "{{ hitchhiker_image_build_args }}"
        target: integration

- name: Set fact for docker container
  set_fact:
    integration_container:
      name: "{{ hitchhiker_config.name }}"
      image: hitchhikerintegration
      description: "{{ hitchhiker_config.name }} integration"
      container_name: "hitchhiker_{{ hitchhiker_config.name | lower | replace('-', '_') | replace(' ', '_') }}"
      restart: unless-stopped
      networks: "{{ hitchhiker_networks | default([]) }}"
      ports: "{{ hitchhiker_config.exposed_ports | default([]) }}"
      volumes: "{{ hitchhiker_default_container_mounts | select('ne', None) | select('ne', '') | select('string') | list | unique }}"
      logging:
        driver: journald
        options:
          tag: "{{ hitchhiker_config.name }}"

- name: Set facts for later tasks
  set_fact:
    client_id: "{{ hitchhiker_config.url.external }}/"
    docker_containers: |
      {
        "hitchhiker_{{ hitchhiker_config.name }}": {{ integration_container }}
      }

- name: Template out the customization file
  template:
    src: homeassistant/customization.yaml.j2
    dest: "{{ hitchhiker_config.storage.config }}/customization.yaml"
  register: customization_file

- name: Template out the configuration file
  template:
    src: homeassistant/configuration.yaml.j2
    dest: "{{ hitchhiker_config.storage.config }}/configuration.yaml"
  register: configuration_file

-